services:
  mysql:
    image: mysql:latest
    container_name: mysql_api_gateway
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codigodb
    ports:
      - "3309:3306"
    volumes:
      - ./mysql:/var/lib/mysql
