server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3309/codigodb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    gateway:
      default-filters:
        - name: AuthenticationFilter
          args:
            name: AuthenticationFilter
      routes:
        - id: voucher
          uri: http://localhost:8082
          predicates:
            - Path=/api/voucher/**
          filters:
            - RewritePath=/api/voucher/(?<segment>.*), /voucher/${segment}
        - id: payment-method
          uri: http://localhost:8082
          predicates:
            - Path=/api/payment-method/**
          filters:
            - RewritePath=/api/payment-method/(?<segment>.*), /payment-method/${segment}
        - id: promo-code
          uri: http://localhost:8081
          predicates:
            - Path=/promo-code/**