/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.codigo.microservices.voucher.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class VoucherCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4809274599670123404L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VoucherCreatedEvent\",\"namespace\":\"com.codigo.microservices.voucher.event\",\"fields\":[{\"name\":\"voucherId\",\"type\":\"string\",\"doc\":\"Unique identifier for the voucher\"},{\"name\":\"quantity\",\"type\":\"int\",\"doc\":\"Quantity of vouchers created\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<VoucherCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<VoucherCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<VoucherCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<VoucherCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<VoucherCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this VoucherCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a VoucherCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a VoucherCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static VoucherCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for the voucher */
  private java.lang.CharSequence voucherId;
  /** Quantity of vouchers created */
  private int quantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VoucherCreatedEvent() {}

  /**
   * All-args constructor.
   * @param voucherId Unique identifier for the voucher
   * @param quantity Quantity of vouchers created
   */
  public VoucherCreatedEvent(java.lang.CharSequence voucherId, java.lang.Integer quantity) {
    this.voucherId = voucherId;
    this.quantity = quantity;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return voucherId;
    case 1: return quantity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: voucherId = (java.lang.CharSequence)value$; break;
    case 1: quantity = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'voucherId' field.
   * @return Unique identifier for the voucher
   */
  public java.lang.CharSequence getVoucherId() {
    return voucherId;
  }


  /**
   * Sets the value of the 'voucherId' field.
   * Unique identifier for the voucher
   * @param value the value to set.
   */
  public void setVoucherId(java.lang.CharSequence value) {
    this.voucherId = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return Quantity of vouchers created
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * Quantity of vouchers created
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Creates a new VoucherCreatedEvent RecordBuilder.
   * @return A new VoucherCreatedEvent RecordBuilder
   */
  public static com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder newBuilder() {
    return new com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder();
  }

  /**
   * Creates a new VoucherCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VoucherCreatedEvent RecordBuilder
   */
  public static com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder newBuilder(com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder other) {
    if (other == null) {
      return new com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder();
    } else {
      return new com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new VoucherCreatedEvent RecordBuilder by copying an existing VoucherCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new VoucherCreatedEvent RecordBuilder
   */
  public static com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder newBuilder(com.codigo.microservices.voucher.event.VoucherCreatedEvent other) {
    if (other == null) {
      return new com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder();
    } else {
      return new com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for VoucherCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VoucherCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<VoucherCreatedEvent> {

    /** Unique identifier for the voucher */
    private java.lang.CharSequence voucherId;
    /** Quantity of vouchers created */
    private int quantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.voucherId)) {
        this.voucherId = data().deepCopy(fields()[0].schema(), other.voucherId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing VoucherCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.codigo.microservices.voucher.event.VoucherCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.voucherId)) {
        this.voucherId = data().deepCopy(fields()[0].schema(), other.voucherId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'voucherId' field.
      * Unique identifier for the voucher
      * @return The value.
      */
    public java.lang.CharSequence getVoucherId() {
      return voucherId;
    }


    /**
      * Sets the value of the 'voucherId' field.
      * Unique identifier for the voucher
      * @param value The value of 'voucherId'.
      * @return This builder.
      */
    public com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder setVoucherId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.voucherId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'voucherId' field has been set.
      * Unique identifier for the voucher
      * @return True if the 'voucherId' field has been set, false otherwise.
      */
    public boolean hasVoucherId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'voucherId' field.
      * Unique identifier for the voucher
      * @return This builder.
      */
    public com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder clearVoucherId() {
      voucherId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * Quantity of vouchers created
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * Quantity of vouchers created
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder setQuantity(int value) {
      validate(fields()[1], value);
      this.quantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * Quantity of vouchers created
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantity' field.
      * Quantity of vouchers created
      * @return This builder.
      */
    public com.codigo.microservices.voucher.event.VoucherCreatedEvent.Builder clearQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public VoucherCreatedEvent build() {
      try {
        VoucherCreatedEvent record = new VoucherCreatedEvent();
        record.voucherId = fieldSetFlags()[0] ? this.voucherId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.quantity = fieldSetFlags()[1] ? this.quantity : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<VoucherCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<VoucherCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<VoucherCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<VoucherCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.voucherId);

    out.writeInt(this.quantity);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.voucherId = in.readString(this.voucherId instanceof Utf8 ? (Utf8)this.voucherId : null);

      this.quantity = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.voucherId = in.readString(this.voucherId instanceof Utf8 ? (Utf8)this.voucherId : null);
          break;

        case 1:
          this.quantity = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










