services:
  mysql:
    image: mysql:latest
    container_name: mysql_code
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_db
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
